[package]
name = "tangle-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
description = "Headless command-line interface for Tangle."

[dependencies]
tangle-model.workspace = true
tangle-sim.workspace = true
clap.workspace = true

[lints]
workspace = true
